# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
